big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Linux Foundation AI Landscape
    fullscreen_header: See the interactive landscape at l.lfai.foundation
    size:
      width: 1420
      height: 800
    fullscreen_size:
      width: 1420
      height: 800
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 4
        width: 400
        height: 160
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Deep Learning
        rows: 4
        width: 400
        height: 160
        top: 0
        left: 420
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Reinforcement Learning
        rows: 4
        width: 160
        height: 160
        top: 0
        left: 840
        color: 'rgb(126,115,14)'
        fit_width: true
      - type: HorizontalCategory
        category: Programming
        rows: 4
        width: 200
        height: 160
        top: 0
        left: 1020
        color: 'rgb(87,43,10)'
        fit_width: true
      - type: HorizontalCategory
        category: Security & Privacy
        rows: 4
        width: 125
        height: 160
        top: 0
        left: 1240
        color: 'rgb(165,9,77)'
        fit_width: true
      - type: HorizontalCategory
        category: Natural Language Processing
        rows: 4
        width: 300
        height: 160
        top: 190
        left: 0
        color: 'rgb(29,119,164)'
        fit_width: true
      - type: HorizontalCategory
        category: Data
        rows: 4
        width: 1045
        height: 160
        top: 190
        left: 320
        color: 'rgb(193,83,21)'
        fit_width: true
      - type: HorizontalCategory
        category: Model
        rows: 4
        width: 845
        height: 160
        top: 380
        left: 0
        color: 'rgb(37,81,209)'
        fit_width: true
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 4
        width: 300
        height: 160
        top: 380
        left: 865
        color: 'rgb(179,60,133)'
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 4
        width: 180
        height: 160
        top: 380
        left: 1185
        color: 'rgb(106,44,218)'
        fit_width: true
      - type: HorizontalCategory
        category: Trusted & Responsible AI
        rows: 3
        width: 320
        height: 160
        top: 570
        left: 0
        color: 'rgb(111,12,52)'
        fit_width: true
      - type: LandscapeInfo
        width: 350
        height: 160
        top: 570
        left: 340
        children:
          - type: text
            text: >
              This landscape explores open source artificial intelligence, machine learning, and deep learning projects, and lists the members of the LF AI
              Foundation.
            top: 15
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfai.foundation
            top: 99
            left: 9
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 15
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 55
            title: LF AI Logo
      - type: HorizontalCategory
        category: LF AI Member Company
        rows: 4
        width: 655
        height: 160
        top: 570
        left: 710
        color: 'rgb(124, 200, 182)'
        fit_width: true
test:
  header: LF AI Foundation Interactive Landscape
  section: Graduated LFAI Projects
  logo: acumos.svg
